apiVersion: v1
kind: Service
metadata:
  name: angular-ag-grid-transaction-demo
  labels:
    app: angular-ag-grid-transaction-demo
spec:
  type: LoadBalancer
  selector:
    app: angular-ag-grid-transaction-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
